### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by qualk** [borisgrigorov/CSGO-Discord-rich-presence#5]
'npm start' doesn't work (I use arch btw), and even if i 'cd' into the src folder and start it, says it cannot find module ../config.json. Because there is none!

**Comment by borisgrigorov** [comment]
Sorry, I forgot to add this to README.
You should create file `config.json` in project root directory, it should look like this:

```json
{
    "richOutput": false, 
    "port": 3127,
    "clientId": "793491189625913344",
    "host": "127.0.0.1"
}
```
Port and host should be same as in csgo config.
You can use mine Discord ID.

I will update the README, and I also create fix for catching this error.

**Comment by qualk** [comment]
What is Rich Output? What is client ID? Can there be a parameter to put the Steam Web API key, instead of having to go to a HTML?

**Comment by borisgrigorov** [comment]
Rich output: Something as debug mode -> more output in console.
clientId: Discord application ID, used for recognizing what application it is on Discord, and also to access assets on Discord. (You can create your own [here](https://discord.com/developers).

**Comment by borisgrigorov** [comment]
And you have to go to webpage only once, the key will be saved.
